### ISSUE TITLE
ICR Workshop - suggestions for improvements

### ISSUE THREAD

**Issue by ricarda9** [sbg/icr-workshop#1]
- adding introductory sentence giving context of this analysis: what are maftools, what datasets are being used, what results are expected and who might be interested in that kind of analysis (and why)?
- adding arrows/rectangular boxes to better indicate selections
- Describing objective and give context of each of the activities (1. select file 2. import CWL 3. View results) 
- Numbering each activity might be useful to better see the structure
- Giving a brief explanation of the results

**Comment by mattions** [comment]
closed by #2
